# Generated by Django 5.1.3 on 2025-09-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usersubscription_manual_estimate_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_session_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
