# Generated by Django 5.1.3 on 2025-09-30 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_current_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_limit_override', models.PositiveIntegerField(blank=True, null=True)),
                ('three_d_views_limit_override', models.PositiveIntegerField(blank=True, null=True)),
                ('manual_estimate_limit_override', models.PositiveIntegerField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_package', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
