# Generated by Django 5.1.3 on 2025-10-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_custompackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='manual_estimate_limit',
            field=models.PositiveBigIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='project_limit',
            field=models.PositiveBigIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='three_d_views_limit',
            field=models.PositiveBigIntegerField(default=10),
        ),
    ]
