# Generated by Django 5.1.3 on 2025-09-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_paymenttransaction_paystack_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
